từ_vựng(thích, 3).
từ_vựng(yêu, 3).
từ_vựng(đọc_sách, 3).
từ_vựng(sống, 2).
từ_vựng(học, 2).
từ_vựng(bố, 2).
từ_vựng(mẹ, 2).
từ_vựng(giáo_viên, 2).
từ_vựng(học_giỏi, 2).
từ_vựng(hoc_sinh_giỏi, 2).
từ_vựng(ban_gái, 2).
từ_vựng(học_cùng_lớp, 2).
từ_vựng(yêu_qúy, 2).
từ_vựng(học_sinh, 1).
từ_vựng(giám_đốc, 1).
từ_vựng(nam, 0).
từ_vựng(hà_nội, 0).
từ_vựng(lớp_mười_hai, 0).
từ_vựng(đạt, 0).
từ_vựng(nhi, 0).
từ_vựng(môn_toán, 0).
từ_vựng(lớp, 0).
từ_vựng(thể_thao, 0).
từ_vựng(rất, 0).
từ_vựng(hoa, 0).
từ_vựng(hai_năm, 0).
từ_vựng(họ, 0).
từ_vựng(thư_viện, 0).
từ_vựng(hay, 0).
từ_vựng(lan, 0).
