tu_vung(thích, 3).
tu_vung(yêu, 3).
tu_vung(đọc_sách, 3).
tu_vung(sống_ở, 2).
tu_vung(học, 2).
tu_vung(bố, 2).
tu_vung(mẹ, 2).
tu_vung(giáo_viên, 2).
tu_vung(học_giỏi, 2).
tu_vung(hoc_sinh_giỏi, 2).
tu_vung(ban_gái, 2).
tu_vung(học_cùng_lớp, 2).
tu_vung(yêu_qúy, 2).
tu_vung(học_sinh, 1).
tu_vung(giám_đốc, 1).
tu_vung(nam, 0).
tu_vung(hà_nội, 0).
tu_vung(lớp_mười_hai, 0).
tu_vung(đạt, 0).
tu_vung(nhi, 0).
tu_vung(môn_toán, 0).
tu_vung(lớp, 0).
tu_vung(thể_thao, 0).
tu_vung(rất, 0).
tu_vung(hoa, 0).
tu_vung(hai_năm, 0).
tu_vung(họ, 0).
tu_vung(thư_viện, 0).
tu_vung(hay, 0).
tu_vung(lan, 0).
